import { mapKey } from "../../Elements/Map/types"

export const mapIconsSet: Set<mapKey> = new Set([
    "acre",
    "alagoas",
    "amapa",
    "amazonas",
    "bahia",
    "brasil",
    "brasildot",
    "ceara",
    "distritofederal",
    "espiritosanto",
    "goias",
    "maranhao",
    "matogrosso",
    "matogrossodosul",
    "minasgerais",
    "para",
    "paraiba",
    "parana",
    "pernambuco",
    "piaui",
    "riodejaneiro",
    "riograndedonorte",
    "riograndedosul",
    "rondonia",
    "roraima",
    "santacatarina",
    "saopaulo",
    "sergipe",
    "southamerica",
    "tocantins"
])
