import { iconsMap } from "./types"

import {
    AtlasIcon,
    AztecCalendarSunIcon,
    BastetIcon,
    CavemanIcon,
    CentaurIcon,
    ColiseumIcon,
    ColombianStatueIcon,
    EgyptianBirdIcon,
    EgyptianCatIcon,
    EgyptianPyramidsIcon,
    EgyptianSphinxIcon,
    EgyptianWalkIcon,
    EyeOfHorusIcon,
    GargoyleIcon,
    GreekSphinxIcon,
    GreekTempleIcon,
    IcarusIcon,
    MachuPicchuIcon,
    MayanPyramidIcon,
    MermaidIcon,
    MoaiIcon,
    MountainCaveIcon,
    SaintBasilCathedralIcon,
    SeaCreatureIcon,
    TrojanHorseIcon,
    VenusOfWillendorfIcon,
    AlpacaIcon,
    AmmoniteIcon,
    AnglerFishIcon,
    AnteaterIcon,
    ArmadilloIcon,
    AxolotlIcon,
    BadgerIcon,
    BatIcon,
    BeaverIcon,
    BeeIcon,
    BugIcon,
    ButterflyIcon,
    CamelIcon,
    CapybaraIcon,
    CaterpillarIcon,
    CatIcon,
    ChickenIcon,
    ClownfishIcon,
    CowIcon,
    CrabIcon,
    DeerIcon,
    DodoIcon,
    DogIcon,
    DolphinIcon,
    DonkeyIcon,
    DragonflyIcon,
    DuckIcon,
    ElephantIcon,
    FelineIcon,
    FlamingoIcon,
    FlyingTroutIcon,
    FoxIcon,
    FrogIcon,
    GeckoIcon,
    GoatIcon,
    GooseIcon,
    GorillaIcon,
    HedgehogIcon,
    HorseIcon,
    HummingBirdIcon,
    JellyfishIcon,
    KiwiBirdIcon,
    KoalaIcon,
    LabradorIcon,
    LadybugIcon,
    LynxIcon,
    MantaRayIcon,
    MonkeyIcon,
    NestBirdsIcon,
    OctopusIcon,
    OstrichIcon,
    OwlIcon,
    PandaIcon,
    PangolinIcon,
    PigIcon,
    PolarBearIcon,
    PorcupineIcon,
    PrayingMantisIcon,
    RabbitIcon,
    RamIcon,
    RatIcon,
    RavenIcon,
    RedPandaIcon,
    RhinocerosIcon,
    RoosterIcon,
    SalamanderIcon,
    SharkIcon,
    SheepIcon,
    ShipIcon,
    ShrimpIcon,
    SittingDogIcon,
    SlothIcon,
    SnailIcon,
    SnakeIcon,
    SpiderIcon,
    SpiderWebIcon,
    SquidIcon,
    SquirrelIcon,
    SwanIcon,
    TapirIcon,
    TortoiseIcon,
    TurtleIcon,
    UnicornIcon,
    VelociraptorIcon,
    WhaleIcon,
    ApoteoseIcon,
    ArcosDaLapaIcon,
    BaianaIcon,
    BiquiniIcon,
    BondinhoIcon,
    BrigadeiroIcon,
    BronzeandoIcon,
    CaipirinhaIcon,
    CalendarioBrasileiroIcon,
    CatedralDeBrasiliaIcon,
    ChimarraoIcon,
    CopacabanaIcon,
    CorcovadoIcon,
    CristoRedentorIcon,
    CristoRedentorVistaIcon,
    DesfileCarnavalIcon,
    ElevadorLacerdaIcon,
    FestaJuninaIcon,
    FrevoIcon,
    GuardaSolIcon,
    HavaianaIcon,
    IgrejaDaPampulhaIcon,
    IpanemaIcon,
    MalandroIcon,
    MaracanaIcon,
    MaspIcon,
    MemorialJKIcon,
    MuseuArteContemporaneaIcon,
    PlanaltoIcon,
    PracaTresPoderesIcon,
    PraiaDeIpanemaIcon,
    SambaIcon,
    SelaronIcon,
    TeatroAmazonasIcon,
    EightIcon,
    EmptyIcon,
    EqualIcon,
    FiveIcon,
    FourIcon,
    MinusIcon,
    MinusMinusIcon,
    NineIcon,
    OneIcon,
    PlusIcon,
    PlusPlusIcon,
    SevenIcon,
    SixIcon,
    ThreeIcon,
    TwoIcon,
    ZeroIcon,
    AlienIcon,
    CryingIcon,
    FairyIcon,
    FemaleVampireIcon,
    GhostIcon,
    HappyIcon,
    PersonIcon,
    SadIcon,
    SpyIcon,
    SuperHappyIcon,
    BeerIcon,
    BowlIcon,
    BreadIcon,
    BurgerIcon,
    CakeIcon,
    DrinkIcon,
    IceCreamIcon,
    PizzaIcon,
    AwardIcon,
    BankCardIcon,
    BriefcaseIcon,
    CandleIcon,
    ClapperboardIcon,
    CrownIcon,
    DiceIcon,
    DoubleHeartIcon,
    FilmIcon,
    GlassesIcon,
    GraduationCapIcon,
    HeartIcon,
    HeartPulseIcon,
    KeyIcon,
    MagazineIcon,
    MedalIcon,
    MusicIcon,
    OfficeIcon,
    PaletteIcon,
    PantoneIcon,
    PulseIcon,
    PuzzleIcon,
    RestTimeIcon,
    SparklingIcon,
    TestTubeIcon,
    TrophyIcon,
    UmbrellaIcon,
    CedarIcon,
    FlagIcon,
    GlobeIcon,
    MapIcon,
    MapPinIcon,
    BrokenLinkIcon,
    CalendarIcon,
    ChartIcon,
    ColorFilterIcon,
    CopyIcon,
    DownloadIcon,
    EmailIcon,
    ErrorIcon,
    ExternalIcon,
    EyeCloseIcon,
    EyeOpenIcon,
    FilterIcon,
    GridIcon,
    HomeIcon,
    ListSortedAscendingIcon,
    ListSortedDescendingIcon,
    ListUnorderedIcon,
    MagicWandIcon,
    MoreIcon,
    PaintBucketIcon,
    PencilIcon,
    ProfileIcon,
    ShadowIcon,
    SongLyricIcon,
    TerminalErrorIcon,
    TerminalIcon,
    ToolsIcon,
    TranslateIcon,
    VoiceRecognitionIcon,
    ZoomInIcon,
    ZoomOutIcon,
    BaiduIcon,
    BarbieIcon,
    CSSIcon,
    FacebookIcon,
    FirefoxIcon,
    GithubIcon,
    GoogleIcon,
    HTMLIcon,
    JavaScriptIcon,
    LeetCodeIcon,
    LinkedinIcon,
    McDonaldsIcon,
    MicrosoftIcon,
    ReactIcon,
    SpotifyIcon,
    TumblrIcon,
    WhatsAppIcon,
    WikiPediaIcon,
    YouTubeIcon,
    AcreIcon,
    AlagoasIcon,
    AmapaIcon,
    AmazonasIcon,
    BahiaIcon,
    BrasilDotIcon,
    BrasilIcon,
    CearaIcon,
    DistritoFederalIcon,
    EspiritoSantoIcon,
    GoiasIcon,
    MaranhaoIcon,
    MatoGrossoDoSulIcon,
    MatoGrossoIcon,
    MinasGeraisIcon,
    ParaibaIcon,
    ParaIcon,
    ParanaIcon,
    PernambucoIcon,
    PiauiIcon,
    RioDeJaneiroIcon,
    RioGrandeDoNorteIcon,
    RioGrandeDoSulIcon,
    RondoniaIcon,
    RoraimaIcon,
    SantaCatarinaIcon,
    SaoPauloIcon,
    SergipeIcon,
    SouthAmericaIcon,
    TocantinsIcon,
    NarutoIcon,
    SonicIcon,
    FishermanIcon,
    GrenadeIcon,
    HighTideIcon,
    PaperFrogIcon,
    SchrodingersCatAliveIcon,
    SchrodingersCatDeadIcon,
    SexyIcon,
    ToyBrickIcon,
    AgogoIcon,
    GuitarIcon,
    HeadphoneIcon,
    LoveSongIcon,
    PandeiroIcon,
    PianistIcon,
    SanfonaIcon,
    SurdoIcon,
    TamborimIcon,
    TrianguloIcon,
    BeachIcon,
    CactusIcon,
    CloudIcon,
    DNAIcon,
    EarthIcon,
    FireIcon,
    LeafIcon,
    LightningIcon,
    MeteorIcon,
    PlanetIcon,
    PlantIcon,
    PrismIcon,
    RainbowIcon,
    RainIcon,
    SnowFlakeIcon,
    StarIcon,
    TornadoIcon,
    WaterfallIcon,
    WaveCrestIcon,
    WindyIcon,
    CodeIcon,
    ComputerIcon,
    DiscIcon,
    GamepadIcon,
    LightbulbIcon,
    MegaphoneIcon,
    PhoneIcon,
    PolaroidIcon,
    RobotIcon,
    RocketIcon,
    SmartPhoneIcon,
    TelevisionIcon,
    TrademarkIcon,
    VHSIcon,
    WebsiteIcon,
    MoonIcon,
    PauseIcon,
    PlayIcon,
    SunIcon,
    BikeIcon,
    BusIcon,
    CarIcon,
    CarrierTruckIcon,
    MotorBikeIcon,
    PlaneIcon,
    Skateboarding1Icon,
    Skateboarding2Icon,
    TrainIcon,
    TruckIcon,
    WalkIcon
} from "../Elements"

const allIcons : iconsMap = new Map ( [

    ["atlas", AtlasIcon],
    ["azteccalendarsun", AztecCalendarSunIcon],
    ["bastet", BastetIcon],
    ["caveman", CavemanIcon],
    ["centaur", CentaurIcon],
    ["coliseum", ColiseumIcon],
    ["colombianstatue", ColombianStatueIcon],
    ["egyptianbird", EgyptianBirdIcon],
    ["egyptiancat", EgyptianCatIcon],
    ["egyptianpyramids", EgyptianPyramidsIcon],
    ["egyptiansphinx", EgyptianSphinxIcon],
    ["egyptianwalk", EgyptianWalkIcon],
    ["eyeofhorus", EyeOfHorusIcon],
    ["gargoyle", GargoyleIcon],
    ["greeksphinx", GreekSphinxIcon],
    ["greektemple", GreekTempleIcon],
    ["icarus", IcarusIcon],
    ["machupicchu", MachuPicchuIcon],
    ["mayanpyramid", MayanPyramidIcon],
    ["mermaid", MermaidIcon],
    ["moai", MoaiIcon],
    ["mountaincave", MountainCaveIcon],
    ["saintbasilcathedral", SaintBasilCathedralIcon],
    ["seacreature", SeaCreatureIcon],
    ["trojanhorse", TrojanHorseIcon],
    ["venusofwillendorf", VenusOfWillendorfIcon],
    ["alpaca", AlpacaIcon],
    ["ammonite", AmmoniteIcon],
    ["anglerfish", AnglerFishIcon],
    ["anteater", AnteaterIcon],
    ["armadillo", ArmadilloIcon],
    ["axolotl", AxolotlIcon],
    ["badger", BadgerIcon],
    ["bat", BatIcon],
    ["beaver", BeaverIcon],
    ["bee", BeeIcon],
    ["bug", BugIcon],
    ["butterfly", ButterflyIcon],
    ["camel", CamelIcon],
    ["capybara", CapybaraIcon],
    ["caterpillar", CaterpillarIcon],
    ["cat", CatIcon],
    ["chicken", ChickenIcon],
    ["clownfish", ClownfishIcon],
    ["cow", CowIcon],
    ["crab", CrabIcon],
    ["deer", DeerIcon],
    ["dodo", DodoIcon],
    ["dog", DogIcon],
    ["dolphin", DolphinIcon],
    ["donkey", DonkeyIcon],
    ["dragonfly", DragonflyIcon],
    ["duck", DuckIcon],
    ["elephant", ElephantIcon],
    ["feline", FelineIcon],
    ["flamingo", FlamingoIcon],
    ["flyingtrout", FlyingTroutIcon],
    ["fox", FoxIcon],
    ["frog", FrogIcon],
    ["gecko", GeckoIcon],
    ["goat", GoatIcon],
    ["goose", GooseIcon],
    ["gorilla", GorillaIcon],
    ["hedgehog", HedgehogIcon],
    ["horse", HorseIcon],
    ["hummingbird", HummingBirdIcon],
    ["jellyfish", JellyfishIcon],
    ["kiwibird", KiwiBirdIcon],
    ["koala", KoalaIcon],
    ["labrador", LabradorIcon],
    ["ladybug", LadybugIcon],
    ["lynx", LynxIcon],
    ["mantaray", MantaRayIcon],
    ["monkey", MonkeyIcon],
    ["nestbirds", NestBirdsIcon],
    ["octopus", OctopusIcon],
    ["ostrich", OstrichIcon],
    ["owl", OwlIcon],
    ["panda", PandaIcon],
    ["pangolin", PangolinIcon],
    ["pig", PigIcon],
    ["polarbear", PolarBearIcon],
    ["porcupine", PorcupineIcon],
    ["prayingmantis", PrayingMantisIcon],
    ["rabbit", RabbitIcon],
    ["ram", RamIcon],
    ["rat", RatIcon],
    ["raven", RavenIcon],
    ["redpanda", RedPandaIcon],
    ["rhinoceros", RhinocerosIcon],
    ["rooster", RoosterIcon],
    ["salamander", SalamanderIcon],
    ["shark", SharkIcon],
    ["sheep", SheepIcon],
    ["ship", ShipIcon],
    ["shrimp", ShrimpIcon],
    ["sittingdog", SittingDogIcon],
    ["sloth", SlothIcon],
    ["snail", SnailIcon],
    ["snake", SnakeIcon],
    ["spider", SpiderIcon],
    ["spiderweb", SpiderWebIcon],
    ["squid", SquidIcon],
    ["squirrel", SquirrelIcon],
    ["swan", SwanIcon],
    ["tapir", TapirIcon],
    ["tortoise", TortoiseIcon],
    ["turtle", TurtleIcon],
    ["unicorn", UnicornIcon],
    ["velociraptor", VelociraptorIcon],
    ["whale", WhaleIcon],
    ["apoteose", ApoteoseIcon],
    ["arcosdalapa", ArcosDaLapaIcon],
    ["baiana", BaianaIcon],
    ["biquini", BiquiniIcon],
    ["bondinho", BondinhoIcon],
    ["brigadeiro", BrigadeiroIcon],
    ["bronzeando", BronzeandoIcon],
    ["caipirinha", CaipirinhaIcon],
    ["calendariobrasileiro", CalendarioBrasileiroIcon],
    ["catedraldebrasilia", CatedralDeBrasiliaIcon],
    ["chimarrao", ChimarraoIcon],
    ["copacabana", CopacabanaIcon],
    ["corcovado", CorcovadoIcon],
    ["cristoredentor", CristoRedentorIcon],
    ["cristoredentorvista", CristoRedentorVistaIcon],
    ["desfilecarnaval", DesfileCarnavalIcon],
    ["elevadorlacerda", ElevadorLacerdaIcon],
    ["festajunina", FestaJuninaIcon],
    ["frevo", FrevoIcon],
    ["guardasol", GuardaSolIcon],
    ["havaiana", HavaianaIcon],
    ["igrejadapampulha", IgrejaDaPampulhaIcon],
    ["ipanema", IpanemaIcon],
    ["malandro", MalandroIcon],
    ["maracana", MaracanaIcon],
    ["masp", MaspIcon],
    ["memorialjk", MemorialJKIcon],
    ["museuartecontemporanea", MuseuArteContemporaneaIcon],
    ["planalto", PlanaltoIcon],
    ["pracatrespoderes", PracaTresPoderesIcon],
    ["praiadeipanema", PraiaDeIpanemaIcon],
    ["samba", SambaIcon],
    ["selaron", SelaronIcon],
    ["teatroamazonas", TeatroAmazonasIcon],
    ["eight", EightIcon],
    ["empty", EmptyIcon],
    ["equal", EqualIcon],
    ["five", FiveIcon],
    ["four", FourIcon],
    ["minus", MinusIcon],
    ["minusminus", MinusMinusIcon],
    ["nine", NineIcon],
    ["one", OneIcon],
    ["plus", PlusIcon],
    ["plusplus", PlusPlusIcon],
    ["seven", SevenIcon],
    ["six", SixIcon],
    ["three", ThreeIcon],
    ["two", TwoIcon],
    ["zero", ZeroIcon],
    ["alien", AlienIcon],
    ["crying", CryingIcon],
    ["fairy", FairyIcon],
    ["femalevampire", FemaleVampireIcon],
    ["ghost", GhostIcon],
    ["happy", HappyIcon],
    ["person", PersonIcon],
    ["sad", SadIcon],
    ["spy", SpyIcon],
    ["superhappy", SuperHappyIcon],
    ["beer", BeerIcon],
    ["bowl", BowlIcon],
    ["bread", BreadIcon],
    ["burger", BurgerIcon],
    ["cake", CakeIcon],
    ["drink", DrinkIcon],
    ["icecream", IceCreamIcon],
    ["pizza", PizzaIcon],
    ["award", AwardIcon],
    ["bankcard", BankCardIcon],
    ["briefcase", BriefcaseIcon],
    ["candle", CandleIcon],
    ["clapperboard", ClapperboardIcon],
    ["crown", CrownIcon],
    ["dice", DiceIcon],
    ["doubleheart", DoubleHeartIcon],
    ["film", FilmIcon],
    ["glasses", GlassesIcon],
    ["graduationcap", GraduationCapIcon],
    ["heart", HeartIcon],
    ["heartpulse", HeartPulseIcon],
    ["key", KeyIcon],
    ["magazine", MagazineIcon],
    ["medal", MedalIcon],
    ["music", MusicIcon],
    ["office", OfficeIcon],
    ["palette", PaletteIcon],
    ["pantone", PantoneIcon],
    ["pulse", PulseIcon],
    ["puzzle", PuzzleIcon],
    ["resttime", RestTimeIcon],
    ["sparkling", SparklingIcon],
    ["testtube", TestTubeIcon],
    ["trophy", TrophyIcon],
    ["umbrella", UmbrellaIcon],
    ["cedar", CedarIcon],
    ["flag", FlagIcon],
    ["globe", GlobeIcon],
    ["map", MapIcon],
    ["mappin", MapPinIcon],
    ["brokenlink", BrokenLinkIcon],
    ["calendar", CalendarIcon],
    ["chart", ChartIcon],
    ["colorfilter", ColorFilterIcon],
    ["copy", CopyIcon],
    ["download", DownloadIcon],
    ["email", EmailIcon],
    ["error", ErrorIcon],
    ["external", ExternalIcon],
    ["eyeclose", EyeCloseIcon],
    ["eyeopen", EyeOpenIcon],
    ["filter", FilterIcon],
    ["grid", GridIcon],
    ["home", HomeIcon],
    ["listsortedascending", ListSortedAscendingIcon],
    ["listsorteddescending", ListSortedDescendingIcon],
    ["listunordered", ListUnorderedIcon],
    ["magicwand", MagicWandIcon],
    ["more", MoreIcon],
    ["paintbucket", PaintBucketIcon],
    ["pencil", PencilIcon],
    ["profile", ProfileIcon],
    ["shadow", ShadowIcon],
    ["songlyric", SongLyricIcon],
    ["terminalerror", TerminalErrorIcon],
    ["terminal", TerminalIcon],
    ["tools", ToolsIcon],
    ["translate", TranslateIcon],
    ["voicerecognition", VoiceRecognitionIcon],
    ["zoomin", ZoomInIcon],
    ["zoomout", ZoomOutIcon],
    ["baidu", BaiduIcon],
    ["barbie", BarbieIcon],
    ["css", CSSIcon],
    ["facebook", FacebookIcon],
    ["firefox", FirefoxIcon],
    ["github", GithubIcon],
    ["google", GoogleIcon],
    ["html", HTMLIcon],
    ["javascript", JavaScriptIcon],
    ["leetcode", LeetCodeIcon],
    ["linkedin", LinkedinIcon],
    ["mcdonalds", McDonaldsIcon],
    ["microsoft", MicrosoftIcon],
    ["react", ReactIcon],
    ["spotify", SpotifyIcon],
    ["tumblr", TumblrIcon],
    ["whatsapp", WhatsAppIcon],
    ["wikipedia", WikiPediaIcon],
    ["youtube", YouTubeIcon],
    ["acre", AcreIcon],
    ["alagoas", AlagoasIcon],
    ["amapa", AmapaIcon],
    ["amazonas", AmazonasIcon],
    ["bahia", BahiaIcon],
    ["brasildot", BrasilDotIcon],
    ["brasil", BrasilIcon],
    ["ceara", CearaIcon],
    ["distritofederal", DistritoFederalIcon],
    ["espiritosanto", EspiritoSantoIcon],
    ["goias", GoiasIcon],
    ["maranhao", MaranhaoIcon],
    ["matogrossodosul", MatoGrossoDoSulIcon],
    ["matogrosso", MatoGrossoIcon],
    ["minasgerais", MinasGeraisIcon],
    ["paraiba", ParaibaIcon],
    ["para", ParaIcon],
    ["parana", ParanaIcon],
    ["pernambuco", PernambucoIcon],
    ["piaui", PiauiIcon],
    ["riodejaneiro", RioDeJaneiroIcon],
    ["riograndedonorte", RioGrandeDoNorteIcon],
    ["riograndedosul", RioGrandeDoSulIcon],
    ["rondonia", RondoniaIcon],
    ["roraima", RoraimaIcon],
    ["santacatarina", SantaCatarinaIcon],
    ["saopaulo", SaoPauloIcon],
    ["sergipe", SergipeIcon],
    ["southamerica", SouthAmericaIcon],
    ["tocantins", TocantinsIcon],
    ["naruto", NarutoIcon],
    ["sonic", SonicIcon],
    ["fisherman", FishermanIcon],
    ["grenade", GrenadeIcon],
    ["hightide", HighTideIcon],
    ["paperfrog", PaperFrogIcon],
    ["schrodingerscatalive", SchrodingersCatAliveIcon],
    ["schrodingerscatdead", SchrodingersCatDeadIcon],
    ["sexy", SexyIcon],
    ["toybrick", ToyBrickIcon],
    ["agogo", AgogoIcon],
    ["guitar", GuitarIcon],
    ["headphone", HeadphoneIcon],
    ["lovesong", LoveSongIcon],
    ["pandeiro", PandeiroIcon],
    ["pianist", PianistIcon],
    ["sanfona", SanfonaIcon],
    ["surdo", SurdoIcon],
    ["tamborim", TamborimIcon],
    ["triangulo", TrianguloIcon],
    ["beach", BeachIcon],
    ["cactus", CactusIcon],
    ["cloud", CloudIcon],
    ["dna", DNAIcon],
    ["earth", EarthIcon],
    ["fire", FireIcon],
    ["leaf", LeafIcon],
    ["lightning", LightningIcon],
    ["meteor", MeteorIcon],
    ["planet", PlanetIcon],
    ["plant", PlantIcon],
    ["prism", PrismIcon],
    ["rainbow", RainbowIcon],
    ["rain", RainIcon],
    ["snowflake", SnowFlakeIcon],
    ["star", StarIcon],
    ["tornado", TornadoIcon],
    ["waterfall", WaterfallIcon],
    ["wavecrest", WaveCrestIcon],
    ["windy", WindyIcon],
    ["code", CodeIcon],
    ["computer", ComputerIcon],
    ["disc", DiscIcon],
    ["gamepad", GamepadIcon],
    ["lightbulb", LightbulbIcon],
    ["megaphone", MegaphoneIcon],
    ["phone", PhoneIcon],
    ["polaroid", PolaroidIcon],
    ["robot", RobotIcon],
    ["rocket", RocketIcon],
    ["smartphone", SmartPhoneIcon],
    ["television", TelevisionIcon],
    ["trademark", TrademarkIcon],
    ["vhs", VHSIcon],
    ["website", WebsiteIcon],
    ["moon", MoonIcon],
    ["pause", PauseIcon],
    ["play", PlayIcon],
    ["sun", SunIcon],
    ["bike", BikeIcon],
    ["bus", BusIcon],
    ["car", CarIcon],
    ["carriertruck", CarrierTruckIcon],
    ["motorbike", MotorBikeIcon],
    ["plane", PlaneIcon],
    ["skateboarding1", Skateboarding1Icon],
    ["skateboarding2", Skateboarding2Icon],
    ["train", TrainIcon],
    ["truck", TruckIcon],
    ["walk", WalkIcon]
])

export { allIcons }