const groupsIcons: Map<string, string> = new Map([
	["theme", "website"],
	["rainbow", "rainbow"],
	["famous media", "clapperboard"],
	["brands", "megaphone"],
	["places", "mappin"],
	["tech", "computer"],
	["schemes", "palette"]
])

const custom: Map<string, string> = new Map([
	["firefox", "firefox"],
	["dominos", "pizza"],
	["coca-cola", "drink"],
	["pepsi", "drink"],
	["bk", "burger"],
	["mcdonalds", "mcdonalds"],
	["lego", "toybrick"],
	["master", "bankcard"],
	["visa", "bankcard"],
	["national geographic", "magazine"],
	["bee", "bee"],
	["emo", "crying"],
	["bmo", "gamepad"],
	["adventure time", "crown"],
	["naruto", "naruto"],
	["cosmo and wanda", "magicwand"],
	["fairly odd parents", "magicwand"],
	["barbie", "barbie"],
	["sonic", "sonic"],
	["brasil", "brasil"],
	["mexico", "icecream"],
	["rioDeJaneiro", "riodejaneiro"],
	["china", "star"],
	["lebanon", "cedar"],
	["syria", "star"],
	["baidu", "baidu"],
	["facebook", "facebook"],
	["google", "google"],
	["microsoft", "microsoft"],
	["spotify", "spotify"],
	["tumblr", "tumblr"],
	["whatsapp", "whatsapp"],
	["wikipedia", "wikipedia"],
	["youtube", "youtube"],
	["rgb", "colorfilter"],
	["cmyk", "colorfilter"],
	["mac16", "terminal"],
	["riscOS16", "terminal"],
	["web basics", "website"],
	["grayscale16", "shadow"],
	["grayscale4", "shadow"],
	["crayola10", "pencil"],
	["crayola12", "pencil"],
	["munsellCrayola", "pencil"],
	["newtown", "prism"],
	["vhs", "television"]
])

export default { group: groupsIcons, custom: custom }
