/****************************/
/*                          */
/*    Icons from Ancient    */
/*                          */
/****************************/
import {
    AtlasIcon,
    AztecCalendarSunIcon,
    BastetIcon,
    CavemanIcon,
    CentaurIcon,
    ColiseumIcon,
    ColombianStatueIcon,
    EgyptianBirdIcon,
    EgyptianCatIcon,
    EgyptianPyramidsIcon,
    EgyptianSphinxIcon,
    EgyptianWalkIcon,
    EyeOfHorusIcon,
    GargoyleIcon,
    GreekSphinxIcon,
    GreekTempleIcon,
    IcarusIcon,
    MachuPicchuIcon,
    MayanPyramidIcon,
    MermaidIcon,
    MoaiIcon,
    MountainCaveIcon,
    SaintBasilCathedralIcon,
    SeaCreatureIcon,
    TrojanHorseIcon,
    VenusOfWillendorfIcon
} from "./Ancient"

/****************************/
/*                          */
/*    Icons from Animals    */
/*                          */
/****************************/
import {
    AlpacaIcon,
    AmmoniteIcon,
    AnglerFishIcon,
    AnteaterIcon,
    ArmadilloIcon,
    AxolotlIcon,
    BadgerIcon,
    BatIcon,
    BeaverIcon,
    BeeIcon,
    BugIcon,
    ButterflyIcon,
    CamelIcon,
    CapybaraIcon,
    CatIcon,
    CaterpillarIcon,
    ChickenIcon,
    ClownfishIcon,
    CowIcon,
    CrabIcon,
    DeerIcon,
    DodoIcon,
    DogIcon,
    DolphinIcon,
    DonkeyIcon,
    DragonflyIcon,
    DuckIcon,
    ElephantIcon,
    FelineIcon,
    FlamingoIcon,
    FlyingTroutIcon,
    FoxIcon,
    FrogIcon,
    GeckoIcon,
    GoatIcon,
    GooseIcon,
    GorillaIcon,
    HedgehogIcon,
    HorseIcon,
    HummingBirdIcon,
    JellyfishIcon,
    KiwiBirdIcon,
    KoalaIcon,
    LabradorIcon,
    LadybugIcon,
    LynxIcon,
    MantaRayIcon,
    MonkeyIcon,
    NestBirdsIcon,
    OctopusIcon,
    OstrichIcon,
    OwlIcon,
    PandaIcon,
    PangolinIcon,
    PigIcon,
    PolarBearIcon,
    PorcupineIcon,
    PrayingMantisIcon,
    RabbitIcon,
    RamIcon,
    RatIcon,
    RavenIcon,
    RedPandaIcon,
    RhinocerosIcon,
    RoosterIcon,
    SalamanderIcon,
    SharkIcon,
    SheepIcon,
    ShipIcon,
    ShrimpIcon,
    SittingDogIcon,
    SlothIcon,
    SnailIcon,
    SnakeIcon,
    SpiderIcon,
    SpiderWebIcon,
    SquidIcon,
    SquirrelIcon,
    SwanIcon,
    TapirIcon,
    TortoiseIcon,
    TurtleIcon,
    UnicornIcon,
    VelociraptorIcon,
    WhaleIcon
} from "./Animals"

/***************************/
/*                         */
/*    Icons from Brasil    */
/*                         */
/***************************/
import {
    ApoteoseIcon,
    ArcosDaLapaIcon,
    BaianaIcon,
    BiquiniIcon,
    BondinhoIcon,
    BrigadeiroIcon,
    BronzeandoIcon,
    CaipirinhaIcon,
    CalendarioBrasileiroIcon,
    CatedralDeBrasiliaIcon,
    ChimarraoIcon,
    CopacabanaIcon,
    CorcovadoIcon,
    CristoRedentorIcon,
    DesfileCarnavalIcon,
    ElevadorLacerdaIcon,
    FestaJuninaIcon,
    FrevoIcon,
    GuardaSolIcon,
    HavaianaIcon,
    IgrejaDaPampulhaIcon,
    IpanemaIcon,
    MalandroIcon,
    MaracanaIcon,
    MaspIcon,
    MemorialJKIcon,
    MuseuArteContemporaneaIcon,
    PlanaltoIcon,
    PracaTresPoderesIcon,
    PraiaDeIpanemaIcon,
    SambaIcon,
    SelaronIcon,
    TeatroAmazonasIcon
} from "./Brasil"

/*******************************/
/*                             */
/*    Icons from Characters    */
/*                             */
/*******************************/
import {
    EightIcon,
    EmptyIcon,
    EqualIcon,
    FiveIcon,
    FourIcon,
    MinusIcon,
    MinusMinusIcon,
    NineIcon,
    OneIcon,
    PlusIcon,
    PlusPlusIcon,
    SevenIcon,
    SixIcon,
    ThreeIcon,
    TwoIcon,
    ZeroIcon
} from "./Characters"

/**************************/
/*                        */
/*    Icons from Faces    */
/*                        */
/**************************/
import {
    AlienIcon,
    CryingIcon,
    FairyIcon,
    FemaleVampireIcon,
    GhostIcon,
    HappyIcon,
    PersonIcon,
    SadIcon,
    SpyIcon,
    SuperHappyIcon
} from "./Faces"

/*************************/
/*                       */
/*    Icons from Food    */
/*                       */
/*************************/
import {
    BeerIcon,
    BowlIcon,
    BreadIcon,
    BurgerIcon,
    CakeIcon,
    DrinkIcon,
    IceCreamIcon,
    PizzaIcon
} from "./Food"

/****************************/
/*                          */
/*    Icons from General    */
/*                          */
/****************************/
import {
    AwardIcon,
    BankCardIcon,
    BriefcaseIcon,
    CandleIcon,
    ClapperboardIcon,
    CrownIcon,
    DiceIcon,
    DoubleHeartIcon,
    FilmIcon,
    GlassesIcon,
    GraduationCapIcon,
    HeartIcon,
    HeartPulseIcon,
    KeyIcon,
    MagazineIcon,
    MedalIcon,
    MusicIcon,
    OfficeIcon,
    PaletteIcon,
    PantoneIcon,
    PulseIcon,
    PuzzleIcon,
    RestTimeIcon,
    SparklingIcon,
    TestTubeIcon,
    TrophyIcon,
    UmbrellaIcon
} from "./General"

/******************************/
/*                            */
/*    Icons from Geography    */
/*                            */
/******************************/
import {
    CedarIcon,
    FlagIcon,
    GlobeIcon,
    MapIcon,
    MapPinIcon
} from "./Geography"

/******************************/
/*                            */
/*    Icons from Interface    */
/*                            */
/******************************/
import {
    AnticlockwiseIcon,
    ArrowIcon,
    BrokenLinkIcon,
    BrushIcon,
    CalendarIcon,
    ChartIcon,
    ClockwiseIcon,
    ColorFilterIcon,
    CopyIcon,
    DiagonalArrowIcon,
    DownloadIcon,
    EmailIcon,
    ErrorIcon,
    ExternalIcon,
    EyeCloseIcon,
    EyeOpenIcon,
    FilterIcon,
    FilterOffIcon,
    GridIcon,
    HomeIcon,
    ListSortedAscendingIcon,
    ListSortedDescendingIcon,
    ListUnorderedIcon,
    MagicWandIcon,
    MoreIcon,
    PaintBucketIcon,
    PauseIcon,
    PencilIcon,
    PlayIcon,
    ProfileIcon,
    RulerIcon,
    ShadowIcon,
    SongLyricIcon,
    TerminalIcon,
    TerminalErrorIcon,
    ToolsIcon,
    TranslateIcon,
    TrashIcon,
    VoiceRecognitionIcon,
    ZoomInIcon,
    ZoomOutIcon
} from "./Interface"

/*************************/
/*                       */
/*    Icons from Logo    */
/*                       */
/*************************/
import {
    BaiduIcon,
    CSSIcon,
    FacebookIcon,
    FirefoxIcon,
    GithubIcon,
    GoogleIcon,
    HTMLIcon,
    JavaScriptIcon,
    LeetCodeIcon,
    LinkedinIcon,
    McDonaldsIcon,
    MicrosoftIcon,
    ReactIcon,
    SpotifyIcon,
    TumblrIcon,
    WhatsAppIcon,
    WikiPediaIcon,
    YouTubeIcon
} from "./Logo"

/************************/
/*                      */
/*    Icons from Map    */
/*                      */
/************************/
import {
    AcreIcon,
    AlagoasIcon,
    AmapaIcon,
    AmazonasIcon,
    BahiaIcon,
    BrasilIcon,
    BrasilDotIcon,
    CearaIcon,
    DistritoFederalIcon,
    EspiritoSantoIcon,
    GoiasIcon,
    MaranhaoIcon,
    MatoGrossoIcon,
    MatoGrossoDoSulIcon,
    MinasGeraisIcon,
    ParaIcon,
    ParaibaIcon,
    ParanaIcon,
    PernambucoIcon,
    PiauiIcon,
    RioDeJaneiroIcon,
    RioGrandeDoNorteIcon,
    RioGrandeDoSulIcon,
    RondoniaIcon,
    RoraimaIcon,
    SantaCatarinaIcon,
    SaoPauloIcon,
    SergipeIcon,
    SouthAmericaIcon,
    TocantinsIcon
} from "./Map"

/**************************/
/*                        */
/*    Icons from Media    */
/*                        */
/**************************/
import { BarbieIcon, NarutoIcon, SonicIcon } from "./Media"

/*************************/
/*                       */
/*    Icons from Misc    */
/*                       */
/*************************/
import {
    FishermanIcon,
    GrenadeIcon,
    HighTideIcon,
    PaperFrogIcon,
    SchrodingersCatAliveIcon,
    SchrodingersCatDeadIcon,
    SexyIcon,
    ToyBrickIcon
} from "./Misc"

/*************************************/
/*                                   */
/*    Icons from MusicInstruments    */
/*                                   */
/*************************************/
import {
    AgogoIcon,
    GuitarIcon,
    HeadphoneIcon,
    LoveSongIcon,
    PandeiroIcon,
    PianistIcon,
    SanfonaIcon,
    SurdoIcon,
    TamborimIcon,
    TrianguloIcon
} from "./MusicInstruments"

/***************************/
/*                         */
/*    Icons from Nature    */
/*                         */
/***************************/
import {
    BeachIcon,
    CactusIcon,
    CloudIcon,
    DNAIcon,
    EarthIcon,
    FireIcon,
    LeafIcon,
    LightningIcon,
    MeteorIcon,
    MoonIcon,
    PlanetIcon,
    PlantIcon,
    PrismIcon,
    RainIcon,
    RainbowIcon,
    SnowFlakeIcon,
    StarIcon,
    SunIcon,
    TornadoIcon,
    WaterfallIcon,
    WaveCrestIcon,
    WindyIcon
} from "./Nature"

/*************************/
/*                       */
/*    Icons from Tech    */
/*                       */
/*************************/
import {
    CodeIcon,
    ComputerIcon,
    DiscIcon,
    GamepadIcon,
    LightbulbIcon,
    MegaphoneIcon,
    PhoneIcon,
    PolaroidIcon,
    RobotIcon,
    RocketIcon,
    SmartPhoneIcon,
    TelevisionIcon,
    TrademarkIcon,
    VHSIcon,
    WebsiteIcon
} from "./Tech"

/*****************************/
/*                           */
/*    Icons from Vehicles    */
/*                           */
/*****************************/
import {
    BikeIcon,
    BusIcon,
    CarIcon,
    CarrierTruckIcon,
    MotorBikeIcon,
    PlaneIcon,
    Skateboarding1Icon,
    Skateboarding2Icon,
    TrainIcon,
    TruckIcon,
    WalkIcon
} from "./Vehicles"

export {
    AtlasIcon,
    AztecCalendarSunIcon,
    BastetIcon,
    CavemanIcon,
    CentaurIcon,
    ColiseumIcon,
    ColombianStatueIcon,
    EgyptianBirdIcon,
    EgyptianCatIcon,
    EgyptianPyramidsIcon,
    EgyptianSphinxIcon,
    EgyptianWalkIcon,
    EyeOfHorusIcon,
    GargoyleIcon,
    GreekSphinxIcon,
    GreekTempleIcon,
    IcarusIcon,
    MachuPicchuIcon,
    MayanPyramidIcon,
    MermaidIcon,
    MoaiIcon,
    MountainCaveIcon,
    SaintBasilCathedralIcon,
    SeaCreatureIcon,
    TrojanHorseIcon,
    VenusOfWillendorfIcon,
    AlpacaIcon,
    AmmoniteIcon,
    AnglerFishIcon,
    AnteaterIcon,
    ArmadilloIcon,
    AxolotlIcon,
    BadgerIcon,
    BatIcon,
    BeaverIcon,
    BeeIcon,
    BugIcon,
    ButterflyIcon,
    CamelIcon,
    CapybaraIcon,
    CatIcon,
    CaterpillarIcon,
    ChickenIcon,
    ClownfishIcon,
    CowIcon,
    CrabIcon,
    DeerIcon,
    DodoIcon,
    DogIcon,
    DolphinIcon,
    DonkeyIcon,
    DragonflyIcon,
    DuckIcon,
    ElephantIcon,
    FelineIcon,
    FlamingoIcon,
    FlyingTroutIcon,
    FoxIcon,
    FrogIcon,
    GeckoIcon,
    GoatIcon,
    GooseIcon,
    GorillaIcon,
    HedgehogIcon,
    HorseIcon,
    HummingBirdIcon,
    JellyfishIcon,
    KiwiBirdIcon,
    KoalaIcon,
    LabradorIcon,
    LadybugIcon,
    LynxIcon,
    MantaRayIcon,
    MonkeyIcon,
    NestBirdsIcon,
    OctopusIcon,
    OstrichIcon,
    OwlIcon,
    PandaIcon,
    PangolinIcon,
    PigIcon,
    PolarBearIcon,
    PorcupineIcon,
    PrayingMantisIcon,
    RabbitIcon,
    RamIcon,
    RatIcon,
    RavenIcon,
    RedPandaIcon,
    RhinocerosIcon,
    RoosterIcon,
    SalamanderIcon,
    SharkIcon,
    SheepIcon,
    ShipIcon,
    ShrimpIcon,
    SittingDogIcon,
    SlothIcon,
    SnailIcon,
    SnakeIcon,
    SpiderIcon,
    SpiderWebIcon,
    SquidIcon,
    SquirrelIcon,
    SwanIcon,
    TapirIcon,
    TortoiseIcon,
    TurtleIcon,
    UnicornIcon,
    VelociraptorIcon,
    WhaleIcon,
    ApoteoseIcon,
    ArcosDaLapaIcon,
    BaianaIcon,
    BiquiniIcon,
    BondinhoIcon,
    BrigadeiroIcon,
    BronzeandoIcon,
    CaipirinhaIcon,
    CalendarioBrasileiroIcon,
    CatedralDeBrasiliaIcon,
    ChimarraoIcon,
    CopacabanaIcon,
    CorcovadoIcon,
    CristoRedentorIcon,
    DesfileCarnavalIcon,
    ElevadorLacerdaIcon,
    FestaJuninaIcon,
    FrevoIcon,
    GuardaSolIcon,
    HavaianaIcon,
    IgrejaDaPampulhaIcon,
    IpanemaIcon,
    MalandroIcon,
    MaracanaIcon,
    MaspIcon,
    MemorialJKIcon,
    MuseuArteContemporaneaIcon,
    PlanaltoIcon,
    PracaTresPoderesIcon,
    PraiaDeIpanemaIcon,
    SambaIcon,
    SelaronIcon,
    TeatroAmazonasIcon,
    EightIcon,
    EmptyIcon,
    EqualIcon,
    FiveIcon,
    FourIcon,
    MinusIcon,
    MinusMinusIcon,
    NineIcon,
    OneIcon,
    PlusIcon,
    PlusPlusIcon,
    SevenIcon,
    SixIcon,
    ThreeIcon,
    TwoIcon,
    ZeroIcon,
    AlienIcon,
    CryingIcon,
    FairyIcon,
    FemaleVampireIcon,
    GhostIcon,
    HappyIcon,
    PersonIcon,
    SadIcon,
    SpyIcon,
    SuperHappyIcon,
    BeerIcon,
    BowlIcon,
    BreadIcon,
    BurgerIcon,
    CakeIcon,
    DrinkIcon,
    IceCreamIcon,
    PizzaIcon,
    AwardIcon,
    BankCardIcon,
    BriefcaseIcon,
    CandleIcon,
    ClapperboardIcon,
    CrownIcon,
    DiceIcon,
    DoubleHeartIcon,
    FilmIcon,
    GlassesIcon,
    GraduationCapIcon,
    HeartIcon,
    HeartPulseIcon,
    KeyIcon,
    MagazineIcon,
    MedalIcon,
    MusicIcon,
    OfficeIcon,
    PaletteIcon,
    PantoneIcon,
    PulseIcon,
    PuzzleIcon,
    RestTimeIcon,
    SparklingIcon,
    TestTubeIcon,
    TrophyIcon,
    UmbrellaIcon,
    CedarIcon,
    FlagIcon,
    GlobeIcon,
    MapIcon,
    MapPinIcon,
    AnticlockwiseIcon,
    ArrowIcon,
    BrokenLinkIcon,
    BrushIcon,
    CalendarIcon,
    ChartIcon,
    ClockwiseIcon,
    ColorFilterIcon,
    CopyIcon,
    DiagonalArrowIcon,
    DownloadIcon,
    EmailIcon,
    ErrorIcon,
    ExternalIcon,
    EyeCloseIcon,
    EyeOpenIcon,
    FilterIcon,
    FilterOffIcon,
    GridIcon,
    HomeIcon,
    ListSortedAscendingIcon,
    ListSortedDescendingIcon,
    ListUnorderedIcon,
    MagicWandIcon,
    MoreIcon,
    PaintBucketIcon,
    PauseIcon,
    PencilIcon,
    PlayIcon,
    ProfileIcon,
    RulerIcon,
    ShadowIcon,
    SongLyricIcon,
    TerminalIcon,
    TerminalErrorIcon,
    ToolsIcon,
    TranslateIcon,
    TrashIcon,
    VoiceRecognitionIcon,
    ZoomInIcon,
    ZoomOutIcon,
    BaiduIcon,
    CSSIcon,
    FacebookIcon,
    FirefoxIcon,
    GithubIcon,
    GoogleIcon,
    HTMLIcon,
    JavaScriptIcon,
    LeetCodeIcon,
    LinkedinIcon,
    McDonaldsIcon,
    MicrosoftIcon,
    ReactIcon,
    SpotifyIcon,
    TumblrIcon,
    WhatsAppIcon,
    WikiPediaIcon,
    YouTubeIcon,
    AcreIcon,
    AlagoasIcon,
    AmapaIcon,
    AmazonasIcon,
    BahiaIcon,
    BrasilIcon,
    BrasilDotIcon,
    CearaIcon,
    DistritoFederalIcon,
    EspiritoSantoIcon,
    GoiasIcon,
    MaranhaoIcon,
    MatoGrossoIcon,
    MatoGrossoDoSulIcon,
    MinasGeraisIcon,
    ParaIcon,
    ParaibaIcon,
    ParanaIcon,
    PernambucoIcon,
    PiauiIcon,
    RioDeJaneiroIcon,
    RioGrandeDoNorteIcon,
    RioGrandeDoSulIcon,
    RondoniaIcon,
    RoraimaIcon,
    SantaCatarinaIcon,
    SaoPauloIcon,
    SergipeIcon,
    SouthAmericaIcon,
    TocantinsIcon,
    BarbieIcon,
    NarutoIcon,
    SonicIcon,
    FishermanIcon,
    GrenadeIcon,
    HighTideIcon,
    PaperFrogIcon,
    SchrodingersCatAliveIcon,
    SchrodingersCatDeadIcon,
    SexyIcon,
    ToyBrickIcon,
    AgogoIcon,
    GuitarIcon,
    HeadphoneIcon,
    LoveSongIcon,
    PandeiroIcon,
    PianistIcon,
    SanfonaIcon,
    SurdoIcon,
    TamborimIcon,
    TrianguloIcon,
    BeachIcon,
    CactusIcon,
    CloudIcon,
    DNAIcon,
    EarthIcon,
    FireIcon,
    LeafIcon,
    LightningIcon,
    MeteorIcon,
    MoonIcon,
    PlanetIcon,
    PlantIcon,
    PrismIcon,
    RainIcon,
    RainbowIcon,
    SnowFlakeIcon,
    StarIcon,
    SunIcon,
    TornadoIcon,
    WaterfallIcon,
    WaveCrestIcon,
    WindyIcon,
    CodeIcon,
    ComputerIcon,
    DiscIcon,
    GamepadIcon,
    LightbulbIcon,
    MegaphoneIcon,
    PhoneIcon,
    PolaroidIcon,
    RobotIcon,
    RocketIcon,
    SmartPhoneIcon,
    TelevisionIcon,
    TrademarkIcon,
    VHSIcon,
    WebsiteIcon,
    BikeIcon,
    BusIcon,
    CarIcon,
    CarrierTruckIcon,
    MotorBikeIcon,
    PlaneIcon,
    Skateboarding1Icon,
    Skateboarding2Icon,
    TrainIcon,
    TruckIcon,
    WalkIcon
}
