const interfaceArr = [
    "anticlockwise",
    "arrow",
    "brokenlink",
    "brush",
    "calendar",
    "chart",
    "clockwise",
    "colorfilter",
    "copy",
    "diagonalarrow",
    "download",
    "email",
    "error",
    "external",
    "eyeclose",
    "eyeopen",
    "filter",
    "filteroff",
    "grid",
    "home",
    "listsortedascending",
    "listsorteddescending",
    "listunordered",
    "magicwand",
    "more",
    "paintbucket",
    "pause",
    "pencil",
    "play",
    "profile",
    "ruler",
    "shadow",
    "songlyric",
    "terminal",
    "terminalerror",
    "tools",
    "translate",
    "voicerecognition",
    "zoomin",
    "zoomout"
] as const

type interfaceKey = (typeof interfaceArr)[number]

export type { interfaceKey }
export { interfaceArr }
